spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true
info:
  app:
    name: "gatewayserver"
    description: "Bank Gateway Server application"
    version: "1.0.0"

logging:
  level:
    com:
     cnsn:
       gatewayserver: DEBUG
resilience4j:
  circuitbreaker:
    configs:
      default: # circuitbreaker name here.
        sliding-window-size: 10 # at least monitor 10 request to open or close
        permitted-number-of-calls-in-half-open-state: 2
        failure-rate-threshold: 50 # 50% fail to turn close state
        wait-duration-in-open-state:
          seconds: 10

